# Generated by Django 4.0.1 on 2022-01-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('desciption', models.TextField()),
                ('poster_link', models.URLField()),
                ('from_dt', models.DateTimeField()),
                ('to_dt', models.DateTimeField()),
                ('deadline', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
